import { useEffect, useState } from 'react'

// berlin-places.json is generated by `npm run places` (scripts/fetch-berlin-places.mjs)
// — a static, citywide extract, not a live query. See that script for why:
// Overpass is a shared public service that's slow and often times out, but
// Berlin's ~9.5k food/drink POIs are a small, slow-changing dataset that has
// no business being re-fetched on every map pan.
//
// Dynamic import so it lands in its own chunk (fetched after first paint,
// not blocking it) and gets precached by the service worker like everything
// else. Module-level cache means the parse only happens once per session.
let cachedPlaces = null
let loadPromise = null

function loadPlaces() {
  if (!loadPromise) {
    loadPromise = import('../data/berlin-places.json').then((mod) => {
      cachedPlaces = mod.default.map(([name, lat, lng, kind, cuisine, osm_id]) => ({
        name,
        lat,
        lng,
        kind,
        cuisine,
        osm_id,
      }))
      return cachedPlaces
    })
  }
  return loadPromise
}

// Returns the full citywide dataset once loaded (empty array before then).
// Callers pick what to actually render from it — see NearbyLayer, which
// narrows this down to the places nearest the current map center.
export function useNearbyPlaces() {
  const [places, setPlaces] = useState(cachedPlaces)

  useEffect(() => {
    if (cachedPlaces) return
    let cancelled = false
    loadPlaces().then((all) => {
      if (!cancelled) setPlaces(all)
    })
    return () => {
      cancelled = true
    }
  }, [])

  return places || []
}
